continuation_prompt = "â–¶â–¶"
format = "[â”Œâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€> ](bold green)$all$line_break[â”‚](bold green) $directory$line_break[â””â”€$character](bold green) "

[character]
error_symbol = ">"
success_symbol = ">"

[directory]
truncation_length = 5
truncation_symbol = "â€¦/"

[git_status]
modified = "î©³  "
staged = 'î«† \($count)'
untracked = "îª¼ "
up_to_date = "î®´ "
conflicted = "ğŸ˜µ "
diverged = "ï„§  "
ahead = 'ï‰” \(${count}\) '
behind = 'ï‰ \(${count}\) '
deleted = "ï€” "
renamed = "î«  "
format = '([$all_status$ahead_behind]($style) )'